databases:
  - name: cv-database
    databaseName: cv
    user: cv_user
    plan: free

services:
  - type: web
    name: cv-portfolio
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cv-database
          property: connectionString
      - key: APP_KEY
        value: base64:Rzz68lGeiDWUlALy8OCrHkhnT9h9bzmQH9hPuYdjYg4=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://sondoc.io.vn
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: cv-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cv-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: cv-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cv-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cv-database
          property: password
